### ISSUE TITLE
Search box unavailable on the mobile Volumio app

### ISSUE THREAD

**Issue by adamsmutnicki** [patrickkfkan/volumio-youtube2#1]
First of all, I wanted to thank you @patrickkfkan for a great work making this plugin work. 

I use an Android phone to control one of my volumios with a Volumio free app. I've noticed that search box for youtube is unavailable on the scree. Effect is the same on at least 2 different (a brand new and older) Samsung phones. 

Is there a way eg. to move the search box to the middle of the screen from a top menu bar?

**Comment by patrickkfkan** [comment]
Hello,

I think you are looking in the wrong place. You should get in touch with the developer of the app and ask him why the search box is placed off screen. The search box is provided by the UI, of which the plugin has no control.

Regards,
Patrick

**Comment by adamsmutnicki** [comment]
Hi patrickkfkan,
I've assumed that this is a plugin search box, not a generic one, but seems I was wrong. Thank you for clarification and quick response. I'm closing this issue then.
