### ISSUE TITLE
Error on 1.2.2 No Result

### ISSUE THREAD

**Issue by daniel3kk** [patrickkfkan/volumio-youtube2#16]
Hi, 

there is a problem on YouTube2 plugin on volumio3

Nov 15 10:51:02 volumio volumio[1077]: error: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 400 Error: Request to https://www.youtube.com/youtubei/v1/browse?prettyPrint=false&alt=json failed with status 400

Daniel

**Comment by patrickkfkan** [comment]
Fixed in v2.1.0 for Bookworm-based Volumio
