### ISSUE TITLE
music interrupt

### ISSUE THREAD

**Issue by taiwan1frog** [patrickkfkan/volumio-youtube2#2]
When I play music, it will stop at 1/2 or 2/3 of the song. How can I improve this problem?
Thanks you.

**Comment by patrickkfkan** [comment]
From the README:

> ### Playback
>
> The plugin uses [MPD](https://www.musicpd.org/) for playing a video's audio stream. The current version of Volumio still ships with a *really* outdated version of MPD that is not entirely compatible with these streams. So, while a stream will still play, you will likely encounter the following:
>
> 1. Playback abruptly ends at ~3/4 into the stream.
> 2. Seeking is not possible at all.
>
> Until [Volumio Buster](https://community.volumio.org/t/volumio-x86-debian-buster-debugging-party-beta/11899) is officially released (which is expected to include a recent version of MPD), here's a [temporary workaround](https://community.volumio.org/t/mpd-0-21-16-for-volumio-arm-armv7-and-x86/11554) (note: no guarantee that it will not break certain aspects of Volumio - use at own risk).

So [update your MPD](https://community.volumio.org/t/mpd-0-21-16-for-volumio-arm-armv7-and-x86/11554) if you are using Volumio 2.x.

**Comment by taiwan1frog** [comment]
Done. It work perfectly. Thank you.
