### ISSUE TITLE
tried to install but there is no zip file

### ISSUE THREAD

**Issue by rharing** [patrickkfkan/volumio-youtube2#4]
cloned latest git commit d4b0c1557cb90a3f999fa385d47c2636061944b0
doing volumio plugin install gives error:

Error: Command failed: /bin/mv *.zip /tmp/plugins/youtube2.zip
/bin/mv: cannot stat '*.zip': No such file or directory
tried to run install.sh but that only echos that its now inatalled, so how can i install this plugin?thanks in advance

**Comment by patrickkfkan** [comment]
Did you `cd` into the repo directory after cloning? Also what version of Volumio are you installing this on?

**Comment by rharing** [comment]
yes i did and looking here at the sources i do not see a zip either
volumio version is 2.714

**Comment by patrickkfkan** [comment]
There is no zip in the sources. It is created by Volumio during plugin installation. The error indicates that Volumio had failed to create the zip file. What is the full output when you do `volumio plugin install`?

Also how much storage space do you have left on your device? 

You can try creating the zip file yourself by running this command in the repo directory:

```
$ IFS=$'\n'; /usr/bin/minizip -o -9 test.zip $(find -type f -not -name test.zip -printf '%P\n')
```

See if you get any errors and whether the zip file has actually been created:

```
$ ls test.zip
```

Note that you should remove the zip file afterwards to keep the repo directory "clean":

```
$ rm test.zip
```

**Comment by rharing** [comment]
full output:This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/youtube2.zip
/bin/mv: cannot stat '*.zip': No such file or directory

    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at install (/volumio/pluginhelper.js:688:9)
    at Object.<anonymous> (/volumio/pluginhelper.js:749:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
volumio@volumio:~/youtube2-plugin/volumio-youtube2$
but as usual the error was between the keyboard and the back of my chair, could not git pull so i used sudo git pull once i did sudo volumio plugin install it failed on size but gave correct and clear error, thank for your time,

**Comment by rharing** [comment]
hmm made room and did a chown yet still it fails:
volumio@volumio:~/youtube2-plugin/volumio-youtube2$ volumio plugin install

This command will install the plugin on your device

Compressing the plugin
Plugin succesfully compressed
/bin/mv: cannot stat '*.zip': No such file or directory
child_process.js:644
    throw err;
    ^

Error: Command failed: /bin/mv *.zip /tmp/plugins/youtube2.zip
/bin/mv: cannot stat '*.zip': No such file or directory

volumio@volumio:~/youtube2-plugin/volumio-youtube2$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  2.2G  796M  1.3G  39% /imgpart
/dev/loop0      338M  338M     0 100% /static
overlay         1.4G  1.4G     0 100% /
devtmpfs        471M     0  471M   0% /dev
tmpfs           485M  3.3M  482M   1% /dev/shm
tmpfs           485M   17M  469M   4% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           485M     0  485M   0% /sys/fs/cgroup
tmpfs           485M  4.0K  485M   1% /tmp
tmpfs           485M     0  485M   0% /var/spool/cups
tmpfs            20M  1.7M   19M   9% /var/log
tmpfs           485M     0  485M   0% /var/spool/cups/tmp
/dev/mmcblk0p1   61M   59M  1.9M  97% /boot
tmpfs            97M     0   97M   0% /run/user/1000volumio@volumio:~/youtube2-plugin/volumio-youtube2$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p2  2.2G  796M  1.3G  39% /imgpart
/dev/loop0      338M  338M     0 100% /static
overlay         1.4G  1.4G     0 100% /
devtmpfs        471M     0  471M   0% /dev
tmpfs           485M  3.3M  482M   1% /dev/shm
tmpfs           485M   17M  469M   4% /run
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           485M     0  485M   0% /sys/fs/cgroup
tmpfs           485M  4.0K  485M   1% /tmp
tmpfs           485M     0  485M   0% /var/spool/cups
tmpfs            20M  1.7M   19M   9% /var/log
tmpfs           485M     0  485M   0% /var/spool/cups/tmp
/dev/mmcblk0p1   61M   59M  1.9M  97% /boot
tmpfs            97M     0   97M   0% /run/user/1000

**Comment by rharing** [comment]
tmp/plugins exists with correct volumio owner

**Comment by patrickkfkan** [comment]
> could not git pull so i used sudo git pull once i did sudo volumio plugin install it failed on size but gave correct and clear error

When you ssh into Volumio as user `volumio` you should land in the `volumio` home directory, which would already have the correct ownership, so you don't have to do `sudo git...`.  Also, after the initial `git clone`, you should already have the latest files from the repo and you don't need to do further 'git pull'.

Have you tried zipping the files manually as suggested, so that we can see if the error stems from this part of the installation process:

> You can try creating the zip file yourself by running this command in the repo directory:
> 
> ```
> $ IFS=$'\n'; /usr/bin/minizip -o -9 test.zip $(find -type f -not -name test.zip -printf '%P\n')
> ```
> 
> See if you get any errors and whether the zip file has actually been created:
> 
> ```
> $ ls test.zip
> ```
> 
> Note that you should remove the zip file afterwards to keep the repo directory "clean":
> 
> ```
> $ rm test.zip
> ```

**Comment by rharing** [comment]
this command dic create a test.zip file

**Comment by rharing** [comment]
yes after cleaning my pie disc i could install it , thanks for your time
