### ISSUE TITLE
Setup Guide Instructions - OAuth client ID

### ISSUE THREAD

**Issue by bandzii** [patrickkfkan/volumio-youtube2#5]
Hello Patrick,

Really sorry to bother you but I was trying to follow your instructions on setting up the API in Google Developer Console. However, I cannot find steps that you have mentioned in #7. I am guessing Google might have changed the way OAuth client ID's are setup. 

Can you please help or provide updated instructions. Again, apologize for bothering you and for my ignorance. 

Thanks,
Ban.

**Comment by patrickkfkan** [comment]
Hi Ban, I have updated the [setup instructions](https://github.com/patrickkfkan/volumio-youtube2/blob/master/gapi_setup.md). Could you let me know if they work for you?

**Comment by bandzii** [comment]
Hi Patrick, it worked. The only change the guide might need is as following:

- Google has changed and by default trying to filter on youtube under step
#3.4 does not show up any value. One has to manually type the following and
add: https://www.googleapis.com/auth/youtube.readonly.

Hope this will help others. Thank you again for putting this together and
helping the community.

Ban.

**Comment by patrickkfkan** [comment]
> Google has changed and by default trying to filter on youtube under step #3.4 does not show up any value.

I am able to get the values to show with the 'youtube' filter:

![image](https://user-images.githubusercontent.com/55383971/130457048-ea5747da-4b68-40b3-8edb-2a142d2e4cb7.png)

**Comment by Vyacheslav-S** [comment]
**Add to the instructions: you need to add a testuser:**
I was creating a new API today and it didn't work without it!

![image](https://user-images.githubusercontent.com/47851954/152036739-5a77e1a3-0ef0-423b-bb31-77beda544e36.png)

**Comment by patrickkfkan** [comment]
Closing as no longer relevant (Google API Credentials not required since v1.0.1)
